### ISSUE TITLE
lvm disk provisioning errors

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/microservices-infrastructure#816]
If you build a cluster with a different number of control and worker nodes (for example 3 control nodes and 4 worker nodes), you will see an error like:

```
*  google_compute_instance.mi-worker-nodes.3: The disk resource 'projects/asteris-mi/zones/us-central1-a/disks/resching-gce-worker-lvm-01' is already being use
d by 'projects/asteris-mi/zones/us-central1-a/instances/resching-gce-worker-001'
```

It looks like the root cause is using the wrong count variable when provisioning the lvm disks: https://github.com/CiscoCloud/microservices-infrastructure/blob/master/terraform/gce/gce.tf#L81

That looks like it should be using `worker_count`. 

I have confirmed the problem on GCE but, at a glance, it looks like the same problem might exist on AWS. We should double check the other platforms too.

**Comment by ryane** [comment]
fixed by #805

**Comment by siddharthist** [comment]
I'm still getting this error when running `terraform destroy` on GCE with master (commit 370b856de1bc9066caa2a93d5922c3421060101f). I have 1 control, 3 worker nodes. 
```5 error(s) occurred:

* google_compute_disk.mi-control-lvm.0: Error deleting disk: googleapi: Error 400: The disk resource 'lb-mi-control-lvm-01' is already being used by 'lb-mi-control-01', resourceInUseByAnotherResource
* google_compute_disk.mi-control-lvm.2: Error deleting disk: googleapi: Error 400: The disk resource 'lb-mi-control-lvm-03' is already being used by 'lb-mi-control-03', resourceInUseByAnotherResource
* google_compute_disk.mi-control-lvm.1: Error deleting disk: googleapi: Error 400: The disk resource 'lb-mi-control-lvm-02' is already being used by 'lb-mi-control-02', resourceInUseByAnotherResource
* google_compute_disk.mi-worker-lvm.1: Error deleting disk: googleapi: Error 400: The disk resource 'lb-mi-worker-lvm-02' is already being used by 'lb-mi-worker-002', resourceInUseByAnotherResource
* google_compute_disk.mi-worker-lvm.0: Error deleting disk: googleapi: Error 400: The disk resource 'lb-mi-worker-lvm-01' is already being used by 'lb-mi-worker-001', resourceInUseByAnotherResource
```

**Comment by ryane** [comment]
@siddharthist I can't repro the exact error you are seeing. I am not sure how you are ending up with 3 `lb-mi-control-lvm` volumes if you only have 1 control node.

But, I did notice an issue with the lvm config on GCE that perhaps is related: #832
